package org.vadere.state.types;

public enum EikonalSolverType {
	FAST_MARCHING, HIGH_ACCURACY_FAST_MARCHING, FAST_MARCHING_ADAPTIVE, HIGH_ACCURACY_FAST_MARCHING_ADAPTIVE, HIGH_ACCURACY_FAST_MARCHING_DYNAMIC, HIGH_ACCURACY_FAST_MARCHING_DENSITY, FAST_ITERATIVE_METHOD, FAST_SWEEPING_METHOD, NONE;

	public boolean isHighAccuracy() {
		return this == HIGH_ACCURACY_FAST_MARCHING ||
				this == HIGH_ACCURACY_FAST_MARCHING_ADAPTIVE ||
				this == HIGH_ACCURACY_FAST_MARCHING_DENSITY ||
				this == HIGH_ACCURACY_FAST_MARCHING_DYNAMIC;
	}
}
