package org.vadere.util.parallel;

import java.util.concurrent.ExecutionException;

/**
 * Performs a simple parallel operation using the thread pool generated by the
 * ParallelWorkerUtil class.
 * 
 * 
 */
public class CountableParallelWorker<ResultType> extends
		AParallelWorker<ResultType> {
	public CountableParallelWorker(int ID, Work<ResultType> work) {
		super(work);
		this.work.setID(ID);
	}

	@Override
	public void start() {
		this.result = ParallelWorkerUtil.getThreadPool().submit(this.work);
	}

	@Override
	public ResultType finish() throws InterruptedException, ExecutionException {
		return this.result.get();
	}
}
